### ISSUE TITLE
依赖找不到

### ISSUE THREAD

**Issue by mankouzhuya** [feiniaojin/ddd-example-cms#1]
![image](https://github.com/feiniaojin/ddd-example-cms/assets/11942405/5ca93b59-4992-4cd5-a381-68a9a1ec70c6)

**Comment by feiniaojin** [comment]
系统提示:您的邮件被腾讯邮箱判定为垃圾邮件,请编辑后重新发送!

**Comment by mankouzhuya** [comment]
ddd-example-cms-domain 模块里面依赖的   <dependency>
            <groupId>com.feiniaojin</groupId>
            <artifactId>ddd</artifactId>
        </dependency> 不存在

**Comment by mankouzhuya** [comment]
![image](https://github.com/feiniaojin/ddd-example-cms/assets/11942405/fddb194b-ce3f-4769-8592-f6613647b0f2)

**Comment by feiniaojin** [comment]
clone下来编译一下，https://github.com/feiniaojin/ddd
