### ISSUE TITLE
pom 中的一些重复引入和错误引入

### ISSUE THREAD

**Issue by freefunc** [feiniaojin/ddd-example-cms#2]
ddd-archetype中引入了重复的            <dependency>
                <groupId>com.feiniaojin.ddd</groupId>
                <artifactId>ddd-archetype-infrastructure-cache</artifactId>
                <version>${project.version}</version>
            </dependency>
并且在多个模块中引入了  不存在的      <dependency>
            <groupId>com.feiniaojin</groupId>
            <artifactId>ddd</artifactId>
        </dependency>

**Comment by feiniaojin** [comment]
系统提示:您的邮件被腾讯邮箱判定为垃圾邮件,请编辑后重新发送!
