### ISSUE TITLE
类型参数java.lang.String不在类型变量E_ID的范围内

### ISSUE THREAD

**Issue by LesterChang0987** [feiniaojin/ddd-example-cms#4]
我在引入了ddd.jar包之后，在ArticleEntityRepository接口中，提示继承的类中DomainRepository<ArticleEntity, String>中的类型参数java.lang.String不在类型变量E_ID的范围内。具体代码如下：
package com.feiniaojin.dddexample.cms.domain;

import com.feiniaojin.ddd.DomainRepository;

public interface ArticleEntityRepository extends DomainRepository<ArticleEntity, String> {

}

**Comment by chenyurong** [comment]
这里应该是写错了，改成下面这样就好了。

```
public interface ArticleEntityRepository extends DomainRepository<ArticleEntity, EntityId<String>> {
}
```

**Comment by feiniaojin** [comment]
已拿掉ddd包，拉一下代码试试哦
